### ISSUE TITLE
Consume task should not create a file and output.uri should not be set when store=true

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/plugin-kafka#30]
### Expected Behavior

When store = true but my Consume task didn't poll any record, I will check outputs.messagesCount to define behaviour. outputs.uri should simply not be set

### Actual Behaviour

outputs.uri is set with (NaN KiB) size. It looks weird and should simply not be set.
![image](https://user-images.githubusercontent.com/37618489/235205256-e43021d2-eb39-40da-9efc-7c64f1daa889.png)

### Steps To Reproduce

Create a Consume task which returns 0 record

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT

**Comment by loicmathieu** [comment]
I think it is set with an empty file, and this avoid having null check everywhere.
If we change this, we may break compatibility with other tasks (like FileTransform) and possibly existing Flow that didn't check if the file exist before processing it (think Bash or Python script).

So I don't think this is a backward compatible change.

**Comment by brian-mulier-p** [comment]
I close the issue as @loicmathieu provided a fix to put 0B instead of NaN in outputs when it is empty
