### ISSUE TITLE
Poll timeout is too low on certain case to create correctly the connection

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-kafka#32]
in some [cases](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1694010600967069?thread_ts=1693842609.534909&cid=C03FQKXRK3K) (when the user set the `groupId` for examples), the poll is too low to connect on Kafka, and will lead to 0 messages consumed. 
We need to validate the connection before starting the duration counter.

**Comment by loicmathieu** [comment]
There is no way to "validate" a connection in Kafka other than, for eg, fetching the topic list which may open ourself to other kind of issues.
Moreover as anything is async I'm not sure it would solve the issue.

So there is two ways I can think of:
- When there is a consumerGroup, wait for the first rebalance (using a rebalance listener) before polling => this can be complex to implement. Alternatively calling `consumer.subscription()` and waiting for the subscription to be non-empty may work, this needs to be tested.
- Increase the default poll to a higher value (5s or 10s for ex)

**Comment by loicmathieu** [comment]
After a second thought I think that both increasing default pollDuration to 5s and waiting for subscription to happen should be done.

@tchiotludo what do you think of something like that?

```java
if (this.groupId != null) {
    consumer.subscribe(topics);
    while (consumer.subscription().isEmpty()) {
        // wait for consumer subscription to happen
    }
}
```

**Comment by tchiotludo** [comment]
ok good point, maybe add a timeout between subscribe and wait that can't be largest than `maxDuration` or `maxPoll`?

**Comment by tchiotludo** [comment]
ok good point, maybe add a timeout between subscribe and wait that can't be largest than `maxDuration` or `maxPoll`?
